secrets:
 minecraftrclone:
   file: rclone.conf

services:
  traefik:
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesResolvers.le.acme.email=contact@zekro.de"
      - "--certificatesResolvers.le.acme.storage=/etc/certstore/acme.json"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=http"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/config:/etc/traefik/dynamic_conf"
      - "/etc/cert:/etc/cert:ro"
      - "/etc/certstore:/etc/certstore"
      - "/etc/localtime:/etc/localtime:ro"
  
  portainer:
    image: "portainer/portainer-ce:latest"
    volumes:
      - "./portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "https"
      traefik.http.routers.portainer.tls: "true"
      traefik.http.routers.portainer.rule: "Host(`portainer.mc.zekro.de`)"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"

  spigot:
    image: 'ghcr.io/zekrotja/spigot-autobuild:jdk-17'
    restart: always
    environment:
      MC_VERSION: "1.19.1"
      BUILD_CACHING: "true"
      XMS: 2G
      XMX: 4G
      MAX_AGE_BACKUP_FILES: 30d
      PRE_START_BACKUP: "true"
    ports:
      - '25565:25565'
      - '25575:25575'
    volumes:
      - './spigot/config:/etc/mcserver/config'
      - './spigot/plugins:/etc/mcserver/plugins'
      - './spigot/worlds:/etc/mcserver/worlds'
      - './spigot/locals:/etc/mcserver/locals'
    secrets:
      - source: minecraftrclone
        target: rcloneconfig
    labels:
      traefik.enable: "true"
      traefik.http.routers.spigot.entrypoints: "https"
      traefik.http.routers.spigot.tls: "true"
      traefik.http.routers.spigot.rule: "Host(`mc.zekro.de`)"
      traefik.http.services.spigot.loadbalancer.server.port: "8123"

  prometheus:
    image: "prom/prometheus:latest"
    command: "--web.enable-admin-api --config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "18889:80"
    expose:
      - "9090"
    volumes:
      - "./prometheus/config:/etc/prometheus"
    restart: always

  grafana:
    image: "grafana/grafana"
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.routers.grafana.entrypoints: "https"
      traefik.http.routers.grafana.tls: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana.mc.zekro.de`)"